2025-02-20 15:57:29,253 - ERROR - Division by zero occurred
Traceback (most recent call last):
  File "c:\Users\Admin\Documents\GitHub\UnifyAI-Training\Logging-ErrorHandling\file-logging.py", line 10, in <module>
    x = 10 / 0
        ~~~^~~
ZeroDivisionError: division by zero
2025-02-20 16:02:49,041 - DEBUG - Debug message
2025-02-20 16:02:49,041 - INFO - Info message
2025-02-20 16:02:49,042 - WARNING - Warning message
2025-02-20 16:02:49,042 - ERROR - Error message
2025-02-20 16:02:49,042 - CRITICAL - Critical message
